### PR TITLE
added tailwindcss jit compatibility

### LINKED ISSUE #1: Does not work with Tailwind 2.1.x (jit-mode)
Hello,

when using Tailwind 2.1 with active jit-mode, I'm getting this error:

```
ERROR in ./resources/styles/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: node.clone is not a function
    at /home/markus/code/blog/web/app/themes/dev-theme/node_modules/tailwindcss/jit/lib/utils.js:94:35
    at Array.map (<anonymous>)
    at cloneNodes (/home/markus/code/blog/web/app/themes/dev-theme/node_modules/tailwindcss/jit/lib/utils.js:94:16)
    at /home/markus/code/blog/web/app/themes/dev-theme/node_modules/tailwindcss/jit/lib/expandTailwindAtRules.js:257:35
    at LazyResult.runOnRoot (/home/markus/code/blog/web/app/themes/dev-theme/node_modules/postcss/lib/lazy-result.js:303:16)
    at LazyResult.runAsync (/home/markus/code/blog/web/app/themes/dev-theme/node_modules/postcss/lib/lazy-result.js:355:26)
    at LazyResult.async (/home/markus/code/blog/web/app/themes/dev-theme/node_modules/postcss/lib/lazy-result.js:205:30)
    at LazyResult.then (/home/markus/code/blog/web/app/themes/dev-theme/node_modules/postcss/lib/lazy-result.js:190:17)
    at processResult (/home/markus/code/blog/web/app/themes/dev-theme/node_modules/webpack/lib/NormalModule.js:675:19)
    at /home/markus/code/blog/web/app/themes/dev-theme/node_modules/webpack/lib/NormalModule.js:777:5
    at /home/markus/code/blog/web/app/themes/dev-theme/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /home/markus/code/blog/web/app/themes/dev-theme/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/home/markus/code/blog/web/app/themes/dev-theme/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/home/markus/code/blog/web/app/themes/dev-theme/node_modules/postcss-loader/dist/index.js:96:7) 
```

For me it seems, that it's caused by tailwindcss-fl, because the error only occurs, when the plugin is active.

Regards,
Markus

### PR DESCRIPTION
**Pull request by Tim-Wils**
Fixes #1

### CODE REVIEW

**Comment by darrenjacoby** [comment]
Amazing, thanks!

**Comment by darrenjacoby** [comment]
Any reason why Tailwind JIT breaks with `:`? Guessing it has something to do with stackable variants? https://tailwindcss.com/docs/just-in-time-mode#stackable-variants

**Comment by Tim-Wils** [comment]
That was my guess too while debugging :) thanks for merging

**Comment by darrenjacoby** [comment]
No problem, sorry it took so long! Thanks for the PR.

**Comment by thisisjamessmith** [comment]
I'm still seeing this issue with Tailwind in JIT mode? I'm using v.3.0.0 of tailwind-fl, as npm says 3.0.1 doesn't exist, not sure if that's why?
