### ISSUE TITLE
Does not work with Tailwind 2.1.x (jit-mode)

### ISSUE THREAD

**Issue by Sukrams** [soberwp/tailwindcss-fl#1]
Hello,

when using Tailwind 2.1 with active jit-mode, I'm getting this error:

```
ERROR in ./resources/styles/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: node.clone is not a function
    at /home/markus/code/blog/web/app/themes/dev-theme/node_modules/tailwindcss/jit/lib/utils.js:94:35
    at Array.map (<anonymous>)
    at cloneNodes (/home/markus/code/blog/web/app/themes/dev-theme/node_modules/tailwindcss/jit/lib/utils.js:94:16)
    at /home/markus/code/blog/web/app/themes/dev-theme/node_modules/tailwindcss/jit/lib/expandTailwindAtRules.js:257:35
    at LazyResult.runOnRoot (/home/markus/code/blog/web/app/themes/dev-theme/node_modules/postcss/lib/lazy-result.js:303:16)
    at LazyResult.runAsync (/home/markus/code/blog/web/app/themes/dev-theme/node_modules/postcss/lib/lazy-result.js:355:26)
    at LazyResult.async (/home/markus/code/blog/web/app/themes/dev-theme/node_modules/postcss/lib/lazy-result.js:205:30)
    at LazyResult.then (/home/markus/code/blog/web/app/themes/dev-theme/node_modules/postcss/lib/lazy-result.js:190:17)
    at processResult (/home/markus/code/blog/web/app/themes/dev-theme/node_modules/webpack/lib/NormalModule.js:675:19)
    at /home/markus/code/blog/web/app/themes/dev-theme/node_modules/webpack/lib/NormalModule.js:777:5
    at /home/markus/code/blog/web/app/themes/dev-theme/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /home/markus/code/blog/web/app/themes/dev-theme/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/home/markus/code/blog/web/app/themes/dev-theme/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/home/markus/code/blog/web/app/themes/dev-theme/node_modules/postcss-loader/dist/index.js:96:7) 
```

For me it seems, that it's caused by tailwindcss-fl, because the error only occurs, when the plugin is active.

Regards,
Markus

**Comment by darrenjacoby** [comment]
Merged @Tim-Wils PR, I'm guessing it was related to stackable variants. https://tailwindcss.com/docs/just-in-time-mode#stackable-variants

**Comment by garethjohnsdesign** [comment]
Just noticed that this isn't available on npm, it's still at 0.3.0, are you able to update? Also thanks for the plugin really useful

**Comment by garethjohnsdesign** [comment]
Just tried to use this again but isn't on npm, are you able to push up?

**Comment by christianmagill** [comment]
@darrenjacoby, any chance of getting this posted to npm?
